[package]
name = "rune-infer"
description = "A standalone, config-driven, OpenAI-API-compatible model server written in Rust."
version = "0.1.0"
authors = ["Shirsendu Bairagi <shirsendu2001@gmail.com>"]
license = "MIT"
repository = "https://github.com/shba007/rune-infer.git"
edition = "2024"
rust-version = "1.98.1"

[lints.clippy]
too_many_arguments = "allow"
collapsible_if = "allow"

[[bin]]
name = "rune-infer"
path = "src/main.rs"

[features]
default = ["cpu"]
cpu = []
cuda = []
vulkan = []
metal = []

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tokio = { version = "1.53", features = ["full", "sync"] }
tokio-stream = { version = "0.1", features = ["sync"] }
async-stream = "0.3"
axum = { version = "0.8", features = ["macros", "http2", "multipart"] }
tower = "0.5"
tower-http = { version = "0.7", features = ["cors", "trace"] }
notify = "8.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
dotenvy = "0.15"
chrono = { version = "0.4", default-features = false, features = [
	"clock",
	"std",
] }
sha2 = "0.11"
hmac = "0.13"
hex = "0.4"
image = { version = "0.25", default-features = false, features = [
	"png",
	"jpeg",
	"webp",
] }
encoding_rs = "0.8.42"
base64 = "0.23"
clap = { version = "4.4", features = ["derive"] }
reqwest = { version = "0.13.5", features = [
	"json",
	"blocking",
	"multipart",
	"stream",
] }

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = [
	"Win32_System_JobObjects",
	"Win32_Foundation",
	"Win32_System_Threading",
	"Win32_Security",
] }

[target.'cfg(unix)'.dependencies]
libc = "0.2.190"

[profile.dev.package."*"]
opt-level = 3
