[changelog]
header = """
# Changelog\n
All notable changes to this project will be documented in this file.\n
"""
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [Unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
            {% if commit.breaking %}[**breaking**] {% endif %}\
            {{ commit.message | upper_first }}\
            {% if commit.remote.username %} by @{{ commit.remote.username }}{% endif %}\
            {% if commit.remote.pr_number %} in #{{ commit.remote.pr_number }}{% endif %}
    {% endfor %}
{% endfor %}\n
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
	{ message = "^feat", group = "<!-- 0 -->🚀 Features" },
	{ message = "^fix", group = "<!-- 1 -->🐛 Bug Fixes" },
	{ message = "^perf", group = "<!-- 2 -->⚡ Performance" },
	{ message = "^refactor", group = "<!-- 3 -->🚜 Refactor" },
	{ message = "^doc", group = "<!-- 4 -->📚 Documentation" },
	{ message = "^style", group = "<!-- 5 -->🎨 Styling" },
	{ message = "^test", group = "<!-- 6 -->🧪 Testing" },
	{ message = "^chore\\(release\\)", skip = true },
	{ message = "^ci\\(release\\)", skip = true },
	{ message = "^chore: apply code fixes", skip = true },
	{ message = "^chore\\(deps.*\\)", skip = true },
	{ message = "^chore", group = "<!-- 7 -->⚙️ Miscellaneous Tasks" },
	{ message = "^ci", group = "<!-- 8 -->🤖 Continuous Integration" },
	{ body = ".*security", group = "<!-- 9 -->🛡️ Security" },
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9].*"
topo_order = false
sort_commits = "oldest"

[bump]
initial_tag = "v0.1.0"
features_always_bump_minor = true
breaking_always_bump_major = true
