name: Rust Release

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  release:
    if: contains(github.event.head_commit.message, 'ci(release):')
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🛠️ Install Tooling (git-cliff)
        uses: taiki-e/install-action@v2
        with:
          tool: git-cliff

      - name: 📝 Create Release Note
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(grep -m1 '^version =' Cargo.toml | cut -d '"' -f2)
          TAG="v$VERSION"
          git-cliff --current --strip header > RELEASE_NOTES.md

          gh release create "$TAG" \
            --title "$TAG" \
            --notes-file RELEASE_NOTES.md
